steps:
- name: 'gcr.io/kaniko-project/executor:latest'
  args:
    - --destination=gcr.io/extraction-on-demand/github.com/imduffy15/squid-docker:$SHORT_SHA
    - --cache=true
    - --cache-ttl=24h

timeout: 1h

options:
  machineType: 'N1_HIGHCPU_8'
